
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: simple_cms
  password: secretpassword
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: simple_cms_development


test:
  <<: *default
  database: simple_cms_test



production:
  <<: *default
  database: simple_cms_production
  username: simple_cms
  password: <%= ENV['SIMPLE_CMS_DATABASE_PASSWORD'] %>
